// ------------------------------------
// Constants
// ------------------------------------
export const INFORMATION_FETCH_ADD_BEGIN            = 'INFORMATION_FETCH_ADD_BEGIN'
export const INFORMATION_FETCH_ADD_FAILURE          = 'INFORMATION_FETCH_ADD_FAILURE'
export const INFORMATION_FETCH_ADD_SUCCESS          = 'INFORMATION_FETCH_ADD_SUCCESS'

export const INFORMATION_FETCH_LIST_BEGIN           = 'INFORMATION_FETCH_LIST_BEGIN'
export const INFORMATION_FETCH_LIST_FAILURE         = 'INFORMATION_FETCH_LIST_FAILURE'
export const INFORMATIOM_FETCH_LIST_SUCCESS         = 'INFORMATIOM_FETCH_LIST_SUCCESS'

export const INFORMATION_FETCH_EDIT_BEGIN           = 'INFORMATION_FETCH_EDIT_BEGIN'
export const INFORMATION_FETCH_EDIT_FAILURE         = 'INFORMATION_FETCH_EDIT_FAILURE'
export const INFORMATION_FETCH_EDIT_SUCCESS         = 'INFORMATION_FETCH_EDIT_SUCCESS'

export const INFORMATION_FETCH_REMOVE_BEGIN         = 'INFORMATION_FETCH_REMOVE_BEGIN'
export const INFORMATION_FETCH_REMOVE_FAILURE       = 'INFORMATION_FETCH_REMOVE_FAILURE'
export const INFORMATION_FETCH_REMOVE_SUCCESS       = 'INFORMATION_FETCH_REMOVE_SUCCESS'

export const INFORMATION_FETCH_PUSHPOINT_BEGIN      = 'INFORMATION_FETCH_PUSHPOINT_BEGIN'
export const INFORMATION_FETCH_PUSHPOINT_FAILURE    = 'INFORMATION_FETCH_PUSHPOINT_FAILURE'
export const INFORMATION_FETCH_PUSHPOINT_SUCCESS    = 'INFORMATION_FETCH_PUSHPOINT_SUCCESS'